services:
  cacheserver:
    image: amkh4n/url-shortener-unity-server-generic:latest
    ports:
      - "${PORT}:${PORT}"
    entrypoint: "/url-shortener-unity/bin/cacheserver
    -port=${PORT} -reserveAmt=${RESERVE} -memcachedHost=memcached:11211 -dbServerHost=${DBSERVER}"
    restart: unless-stopped
  memcached:
    image: memcached
    entrypoint: memcached --port=11211
    restart: unless-stopped